### ISSUE TITLE
With parallel make, the F90 tests fail

### ISSUE THREAD

**Issue by olebole** [danieljprice/giza#62]
I will take the opportunity to report another small glitch: On Debian, the build by default invokes "make" with parallel tasks (`-j` option). This worked well in the past, but now I see a reproducible failure in `test/F90`:
```
making check in F90
make[3]: Entering directory '/build/giza-1.4.3/test/F90'
make  test-2D test-fortran test-pgaxis
gfortran   -I../../src -g -O2 -ffile-prefix-map=/build/giza-1.4.3=. -fstack-protector-strong -fstack-clash-protection -fcf-protection -c -o test-2D.o test-2D.f90
gfortran   -I../../src -g -O2 -ffile-prefix-map=/build/giza-1.4.3=. -fstack-protector-strong -fstack-clash-protection -fcf-protection -c -o test-fortran.o test-fortran.f90
gfortran   -I../../src -g -O2 -ffile-prefix-map=/build/giza-1.4.3=. -fstack-protector-strong -fstack-clash-protection -fcf-protection -c -o test-pgaxis.o test-pgaxis.f90
Checking for required png files...
ERROR: Required file giza-test.png does not exist.
make[4]: Entering directory '/build/giza-1.4.3/test/F90'
gfortran   -I../../src -g -O2 -ffile-prefix-map=/build/giza-1.4.3=. -fstack-protector-strong -fstack-clash-protection -fcf-protection -c -o test-2D.o test-2D.f90
make[3]: *** [Makefile:1001: check_output_files] Error 1
make[3]: *** Waiting for unfinished jobs....
```
This is minor, because I can force serial build here; however there is probably a dependency missing for the `check_output_files` target.

**Comment by danieljprice** [comment]
thanks, I fixed the dependency here and make -j check does now work on my laptop if I manually press Enter

However, if I try to run the workflow with "make -j check" then I get a hang in the GitHub Actions workflow... one option here would be to try to make most of the tests go to non-interactive devices (like png) instead of the default /xw

I should add that "make -j" works for the main build in the GitHub Actions, just not "make -j check" for the test suite

**Comment by danieljprice** [comment]
I think for the moment we should enforce serial build for "make check" (but can keep a parallel build for the make itself)
